### PR TITLE
Fix heartbeat probe

### LINKED ISSUE #65: Handle FCM Inavlid Argument Error
FCM seems to (newly?) respond to some invalid tokens with an "invalid argument" error.
Sample:
```
error: Error sending FCM message: {
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "[type.googleapis.com/google.firebase.fcm.v1.FcmError](http://type.googleapis.com/google.firebase.fcm.v1.FcmError)",
        "errorCode": "INVALID_ARGUMENT"
      },
      {
        "@type": "[type.googleapis.com/google.rpc.BadRequest](http://type.googleapis.com/google.rpc.BadRequest)",
        "fieldViolations": [
          {
            "field": "message.token",
            "description": "Invalid registration token"
          }
        ]
      }
    ]
  }
}
```

I believe the correct response is to assume the token is invalid and should be removed from the database.
Furthermore, due to the current db query structure we send multiple heartbeat probes for the same token - causing uneccessary server load on both sides.

### PR DESCRIPTION
**Pull request by maxbartunik**
This fixes #65 

Changes
- handle 400 "INVALID_ARGUMENT" response from FCM
- adjust heartbeat query to avoid duplicate heartbeat probes

### CODE REVIEW

**Comment by keszocze** [comment]
> Changes
> 
>     1. handle 400 "INVALID_ARGUMENT" response from FCM
> 
>     2. adjust heartbeat query to avoid duplicate heartbeat probes

I totally see how 1. is handled. What I do not understand is what the new of the DB query changes.

**Review by keszocze — CHANGES_REQUESTED** [review]
> Changes
> 
>     1. handle 400 "INVALID_ARGUMENT" response from FCM
> 
>     2. adjust heartbeat query to avoid duplicate heartbeat probes

I totally see how 1. is handled. What I do not understand is what the new of the DB query changes. Can you please elaborate?

Github is complaining that this branch is out of date with `main`. This is kind of weird to me as that is the branch this PR wants to merge into. If it wasn't out of date, it would make no sense to merge in the first place, or am I missing something?

Anyhow: why do we want to merge into `main` and not `development`?

I pushed to the branch enforcing the style guide. It seems not to be reflected in this PR yet. I don't know how to tell Github to use the latest commit though.

**Comment by maxbartunik** [comment]
I changed the base.
I believe the warning is to claim that the destination branch has commits ahead of the branch to be merged.

**Review by keszocze — APPROVED** [review]
Okay, now that I see why things happen, I am fine with it. :)

**Pull request merged**
